### ISSUE TITLE
Make docroot configurable

### ISSUE THREAD

**Issue by kostajh** [davenuman/bowline#6]
I work on various projects that have `htdocs`, `public_html`, `www`, `drupalroot`, etc. It would be great to have a config variable to specify what the DocumentRoot should be.

Not sure the best way to go about doing that with this project.

**Comment by davenuman** [comment]
I agree in principle that the document root should be configurable but this would be tricky to implement as the path is baked into the apache configuration within the docker image and also used in various scripts. The docroot directory name was chosen because it seemed like the most commonly used in the major hosting companies and other examples. Anyway, I recommend creating a symlink to docroot from your other paths for now (or the other way around if you prefer).
